name: Taikoon UI Checks

on:
  push:
    branches: [main]
    paths:
      - "packages/taikoon-ui/**"
  pull_request:
    paths:
      - "packages/taikoon-ui/**"

jobs:
  check-taikoon-ui:
    runs-on: [taiko-runner]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Svelte check
        working-directory: ./packages/taikoon-ui
        run: pnpm svelte:check

      - name: Linting
        working-directory: ./packages/taikoon-ui
        run: pnpm lint

      - name: Unit tests
        env:
          SKIP_ENV_VALIDATION: "true"
        working-directory: ./packages/taikoon-ui
        run: pnpm test:unit
